---
title: "README"
output: html_document
date: "2025-06-12"
---


# Purpose

The purpose of this project is to evaluate the interest rate dynamics in South Africa since 2000. This is for 2025 Data Science for Economics and Finance 871 project. 

# Data

```{r}

library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(here)

# Importing Global Macro Dataset 
Macro  <- read_csv(here("data", "GMD.csv"))

# Filter the data to South Africa
MzansiMAcro <- Macro %>% filter(countryname == "South Africa")

```


# Visualization Section 


```{r}
# Plotting a graph that showed the years where Inflation has been outside the SARB target range since 2000 
library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(here)


# Plotting a graph that showed the years where Inflation has been outside the SARB target range since 2000 
MzansiMAcro %>% filter(year >=2000 & year<=2024) %>% mutate(outside_target = infl < 3 | infl > 6) %>% ggplot(aes(x = year, y = infl)) +
  geom_line(color = "grey60") +
  geom_point(aes(color = outside_target), size = 3) +
  geom_hline(yintercept = 3, linetype = "dashed", color = "blue") +
  geom_hline(yintercept = 6, linetype = "dashed", color = "blue") +
  scale_color_manual(values = c("FALSE" = "black", "TRUE" = "red"), guide = "none") +
  labs(
    title = "Years with Inflation Outside SARB Target Range (3–6%)",
    x = "Year",
    y = "Inflation Rate (%)"
  ) +
  theme_minimal()

```

```{r}



library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(readr)
library(here)

 #Visualizing the inflation and interest rate trends since 2000

sa_rates_long5 <- MzansiMAcro %>% filter(year >= 2000 & year <= 2024)%>% pivot_longer(cols = c(strate, ltrate, infl),names_to = "rate_type", values_to = "rate")

 ggplot(sa_rates_long5, aes(x = year, y = rate, color = rate_type)) +
  geom_line(linewidth = 1.2) + scale_y_continuous(limits = c(-5, 25)) + scale_x_continuous(breaks = seq(2000, 2025, by = 5)) +
  labs(title = "Inflation and Interest Rate Dynamics in South Africa ",
       x = "Year", y = "Rate (%)",
       color = "Rate Type") +
  theme_minimal() 


```


# Statistical modeling section 

```{r}
 

library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(here)

# Generating a table for inflation persistence from an AR(1) model 

df <- MzansiMAcro %>%
  filter(year >= 2008 & year <= 2024) %>%
  arrange(year) %>%
  mutate(infl_lag1 = lag(infl, 1))

model <- lm(infl ~ infl_lag1, data = df)
fyf<- summary(model)

hibo<-xtable(fyf , caption = "Inflation Persistence in South Africa (2008-2024) \\label{tab4}" )


print.xtable(hibo, 
             # tabular.environment = "longtable",
             floating = TRUE,
             table.placement = 'H',
             # scalebox = 0.3,
             comment = FALSE,
             caption.placement = 'bottom'
             )


```



```{r}


library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(vars)
library(here)


# Generating a table for short-term interest rate equation from the VAR model

clean_df <- MzansiMAcro %>%
  filter(year >= 2000 & year <= 2024) %>%
  dplyr ::select(infl, short_rate = strate, long_rate = ltrate) %>%
  na.omit()

ts_data <- ts(clean_df, start = 2000, frequency = 1)

var_model <- VAR(ts_data, p = 2, type = "const")


short_rate_output <- summary(var_model$varresult$short_rate)$coefficients
short_rate_table <- xtable(short_rate_output, 
                           caption = "VAR Equation for Short-Term Interest Rate \\label{tab34}")
print(short_rate_table, 
      include.rownames = TRUE, 
      caption.placement = "bottom",  comment = FALSE)


```



```{r}

library(tseries)
library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(vars)
library(urca)
library(here)

Macro  <- read_csv(here("data", "GMD.csv"))
MzansiMAcro <- Macro %>% filter(countryname == "South Africa")


# Conducting a Augmented Dickey Fuller test for stationarity 
# Hanjo wanted me to show ADF and PACF tests

adf.test(ts_data[, "infl"])        
adf.test(ts_data[, "short_rate"])  
adf.test(ts_data[, "long_rate"])


# Testing for cointegration of my non-stationary variables 
cajo_test <- ca.jo(ts_data, 
                   type = "trace",     
                   ecdet = "const",    
                   K = 2)              

summary(cajo_test)


clean_df <- MzansiMAcro %>%
  filter(year >= 2000 & year <= 2024) %>%
  dplyr ::select(infl, short_rate = strate, long_rate = ltrate) %>%
  na.omit()

ts_data <- ts(clean_df, start = 2000, frequency = 1)


# Taking the first difference of my data since there is evidence of non-stationarity and no cointegration 

diff_data <- diff(ts_data)  
library(vars)
var_model_diff <- VAR(diff_data, p = 2, type = "const")
summary(var_model_diff)


```


```{r}


library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(vars)
library(here)


# Generating a table for long-term interest rate equation from the VAR model
long_rate_output <- summary(var_model_diff$varresult$long_rate)$coefficients

long_rate_table <- xtable(long_rate_output, 
                          caption = "VAR Equation for Long-Term Interest Rate \\label{tab7}")
print(long_rate_table, 
      include.rownames = TRUE,
      caption.placement = "bottom",
      comment= FALSE) 

```


```{r}


library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(vars)
library(here)

# Generating an Impulse response functions , will be used if necessary , this shows the movement of the variables following a shock 

clean_df <- MzansiMAcro %>%
  filter(year >= 2000 & year <= 2024) %>%
  dplyr ::select(inflation_rate = infl, short_rate = strate, long_rate = ltrate) %>%
  na.omit()

ts_data <- ts(clean_df, start = 2000, frequency = 1)

var_model <- VAR(ts_data, p = 2, type = "const")


irf_result <- irf(var_model,
                  impulse = "inflation_rate",                      
                  response = c("short_rate", "long_rate"),
                  n.ahead = 10,
                  boot = TRUE)
plot(irf_result)



```


# Appendix 

```{r}


library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(vars)

# Generating a table that describes the variables used in the paper 
var_table <- data.frame(
  Variable = c("infl", "strate", "ltrate", "cbrate"),
  Description = c("Inflation rate (%)",
                  "Short-term interest rate (%)",
                  "Long-term interest rate (%)",
                  "Central bank rate (repo rate, %)")
)

vva <- xtable(var_table, caption = "Variable Descriptions\\label{tab21}")


  print.xtable(vva,
             # tabular.environment = "longtable",
             floating = TRUE,
             table.placement = 'H',
             # scalebox = 0.3,
             comment = FALSE,
             caption.placement = 'bottom',
             include.rownames = FALSE
             )



```

```{r}

 

library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(vars)
library(here)

# Generating a table showing inflation since 2000 

 infa <- MzansiMAcro  %>% mutate(year = as.integer(year)) %>%  filter(year >= 2000 & year <= 2024) %>% dplyr::select(Year = year, `Inflation Rate (%)` = infl) 


  thea<-xtable(infa , caption = "Annual Inflation Rate in South Africa (2000–2024) \\label{tab8}" )
  
  print.xtable(thea,
             # tabular.environment = "longtable",
             floating = TRUE,
             table.placement = 'H',
             # scalebox = 0.3,
             comment = FALSE,
             caption.placement = 'bottom',
             include.rownames = FALSE
             )
  
```

```{r}


library(tidyverse)
library(lubridate)
library(huxtable)
library(dplyr)
library(tidyr)
library(xtable)
library(vars)
library(here)

# Generating a table showing the inflation and repo rate post the 2008 peak of inflation

bahn_table <- MzansiMAcro %>%mutate(year = as.integer(year)) %>% 
  filter(year >= 2010 & year <= 2024) %>%
  dplyr::select(Year = year, `Inflation Rate (%)` = infl , `Repo Rate (%)` = cbrate)


haibo<-xtable(bahn_table , caption = "Annual Inflation and Repo Rate in South Africa (2000–2024) \\label{tab9}" )


print.xtable(haibo, 
             floating = TRUE,
             table.placement = 'H',
             comment = FALSE,
             caption.placement = 'bottom',
             include.rownames = FALSE)
```


